### ISSUE TITLE
--allowed-categories not detected

### ISSUE THREAD

**Issue by collaed** [pemre/iptv-cli#1]
Hi,

Brand new install, of npm, then of your scripts; seems very promising, but even copying the basic examples you document, it does not detect the --allowed-categories in filter mode and complains that at least one argument is required.

I would say this is to blame (in the filter command):
if (!args['allowed-**channels**'] && !args['allowed-**channels**']) {
    console.error(`Error: Missing arguments. At least one allowed argument must be used.`);
    return;
  }

**Comment by JavierMartinz** [comment]
@pemre could you please publish the release? I think you missed to do so, after merging this 😅

**Comment by pemre** [comment]
I wasn't active lately, thank you very much 🤗. Just pushed v0.2.1 to npm.
